### ISSUE TITLE
OCP 4.1 baremetal install ends up with cni network uninitialized

### ISSUE THREAD

**Issue by gaord** [openshift/multus-cni#22]
bootstrap cluster can't move on because masters' network is not ready and node neither. It looks like multus pod can't find master plugin to auto generate configuration file. Any suggestion on the problem?

Here is log in multus:
`[core@master1 ~]$ sudo crictl logs f35b68992c2f7
Generating Multus configuration file ...
Attemping to find master plugin configuration, attempt 0
Attemping to find master plugin configuration, attempt 5
Attemping to find master plugin configuration, attempt 10
Attemping to find master plugin configuration, attempt 15
Attemping to find master plugin configuration, attempt 20
Attemping to find master plugin configuration, attempt 25
Attemping to find master plugin configuration, attempt 30
Attemping to find master plugin configuration, attempt 35
Attemping to find master plugin configuration, attempt 40
Attemping to find master plugin configuration, attempt 45
Attemping to find master plugin configuration, attempt 50
Attemping to find master plugin configuration, attempt 55
Attemping to find master plugin configuration, attempt 60
Attemping to find master plugin configuration, attempt 65
Attemping to find master plugin configuration, attempt 70
Attemping to find master plugin configuration, attempt 75
Attemping to find master plugin configuration, attempt 80
Attemping to find master plugin configuration, attempt 85
Attemping to find master plugin configuration, attempt 90`

Here is startup command of the container:

`/bin/bash /entrypoint.sh --multus-conf-file=auto --multus-kubeconfig-file-host=/etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig --namespace-isolation=true --multus-log-level=verbose`

Many thanks.
Ben

**Comment by gaord** [comment]
It's a network issue. get sorted now.

**Comment by EmanueleGallone** [comment]
Hi,
I've got the same problem but I don't think it's a network issue; the machine is reachable through ssh.
Do you know how to solve this kind of issue?
