### ISSUE TITLE
Add support for cilium-cni

### ISSUE THREAD

**Issue by MartijnStraatman** [openshift/multus-cni#41]
**What would you like to be added**:

Add the cilium-cni plugin

**Why is this needed**:

Support for cilium-cni as sdn. With cilium with have some extra features like the cluster-mesh option. As a workaround we copied the cilium-cni binary from  /opt/cni/bin/cilium-cni to /var/lib/cni/bin so the multus picks up cilium

It's not really clear how to configure multus to look in /opt/cni/bin for additional binaries.
There is an additional flag but this is already configured.

**Comment by LorbusChris** [comment]
/reopen
Let's reopen until the following part is properly documented:
> It's not really clear how to configure multus to look in /opt/cni/bin for additional binaries.
> There is an additional flag but this is already configured.
